application: betfair-tennis-api
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*  # This regex directs all routes to main.app
  script: betfair_tennis_api.__init__.app

libraries:
- name: ssl
  version: latest
